### ISSUE TITLE
AttributeError: module 'pdb' has no attribute 'gr_pdb'

### ISSUE THREAD

**Issue by mdoallo** [utn-ba-rf-lab/gr-pdb#3]
Cloné la rama origin/nonlinear compiló con un warning, pero salió (Found Boost: /usr/lib/x86_64-linux-gnu/cmake/Boost-1.71.0/BoostConfig.cmake (found suitable version "1.71.0", minimum required is "1.71.0") found components: date_time program_options filesystem system regex thread unit_test_framework)

Executing: /usr/bin/python3 -u /home/mdoallo/RF-Lab/gr-pdb/examples/Quantify_Experience_1_tono.py

Warning: failed to XInitThreads()
Traceback (most recent call last):
  File "/home/mdoallo/RF-Lab/gr-pdb/examples/Quantify_Experience_1_tono.py", line 242, in <module>
    main()
  File "/home/mdoallo/RF-Lab/gr-pdb/examples/Quantify_Experience_1_tono.py", line 220, in main
    tb = top_block_cls()
  File "/home/mdoallo/RF-Lab/gr-pdb/examples/Quantify_Experience_1_tono.py", line 157, in __init__
    self.pdb_gr_pdb_0 = pdb.gr_pdb(bits,'alaw',255,87.6)
AttributeError: module 'pdb' has no attribute 'gr_pdb'

>>> Done (return code 1)

**Comment by mdoallo** [comment]
Confirmo que tanto la notebook Lenovo (donde no funciona) y la ASUS tienen el mismo GNU Radio versión 3.8.1.0 (Python 3.8.10).
Copié el código AddPython que tenía en la ASUS funcionando a la Lenovo, lo compilé allí y mismo error que ayer.
También comparé los paquete de GNU Radio en ambos equipos y no encontré diferencias de importancia. La ASUS tiene un par de paquetes más que tienen que ver con radio pero son de mi hobby.
Mandé a reinstalar todos los paquetes que tiene por nombre "radio" via aplicación Muon.
Reinicié por si acaso.
Sigue la falla. No parece el selección de Add o Sub.
Mandé a reinstalar todos los paquetes que tiene por nombre "python" via aplicación Muon.
Reinicié por si acaso.
Sigue la falla. No parece el selección de Add o Sub.
